/**
 * Akshar Dental Clinic — Surat Morning
 * Verified public treatment names are presented in a clear, patient-friendly content model.
 * Detailed pages explain the role of each treatment without making diagnostic or outcome claims.
 */
export type AksharService = {
  slug: string;
  number: string;
  title: string;
  eyebrow: string;
  summary: string;
  overview: string;
  considerations: string[];
};

export const aksharServices: AksharService[] = [
  { slug: "dental-checkups-exams", number: "01", title: "Dental checkups & exams", eyebrow: "Preventive care", summary: "Preventive assessment and everyday oral-health guidance.", overview: "A regular dental checkup is a practical moment to talk about your oral health, look for concerns early, and understand the next helpful step. Dr. Aneri can tailor the conversation to your present needs and long-term goals.", considerations: ["Discuss a concern, change, or question", "Review preventive care for teeth and gums", "Leave with a clearer plan for your next step"] },
  { slug: "teeth-cleaning", number: "02", title: "Teeth cleaning", eyebrow: "Professional cleaning", summary: "Professional cleaning that supports healthier teeth and gums.", overview: "Professional cleaning helps remove the buildup that daily brushing may miss. It is a useful part of ongoing oral-health care and a chance to refresh the habits that best support your teeth and gums.", considerations: ["Support everyday gum care", "Refresh your brushing and cleaning routine", "Pair with an exam when appropriate"] },
  { slug: "fillings-restorative-care", number: "03", title: "Fillings & restorative care", eyebrow: "Restore comfort", summary: "Practical treatment to restore comfort and protect natural teeth.", overview: "Restorative care is about protecting the teeth you have and addressing damage or decay with a clear plan. The clinic can walk you through the recommended approach and why it may be useful for your smile.", considerations: ["Understand the condition of the tooth", "Discuss restoration options clearly", "Plan care around comfort and function"] },
  { slug: "teeth-whitening", number: "04", title: "Teeth whitening", eyebrow: "Cosmetic dentistry", summary: "Cosmetic brightening planned around your smile goals.", overview: "Teeth whitening is one of several cosmetic options available at Akshar Dental Clinic. A consultation is a helpful first step to discuss your smile goals, the appearance you would like to refine, and whether whitening suits your needs.", considerations: ["Talk through your cosmetic goal", "Understand suitable whitening options", "Coordinate with other smile treatments if needed"] },
  { slug: "veneers", number: "05", title: "Veneers", eyebrow: "Cosmetic refinement", summary: "Custom cosmetic refinement for shape, colour, and confidence.", overview: "Veneers are a cosmetic option that may help refine tooth shape, colour, or other visual details. A personal consultation gives you the space to discuss the look you want and the options that make sense for your smile.", considerations: ["Discuss shape and colour preferences", "Understand the treatment approach", "Consider how veneers fit a wider smile plan"] },
  { slug: "smile-makeovers", number: "06", title: "Smile makeovers", eyebrow: "Personal smile planning", summary: "A thoughtful cosmetic plan built around your individual features.", overview: "A smile makeover can bring several cosmetic considerations into one thoughtful discussion. The starting point is your own goals: what you would like to change, what you would like to keep, and how you want to feel about your smile.", considerations: ["Share the look you are hoping for", "Consider a tailored combination of options", "Build a staged, understandable plan"] },
  { slug: "pediatric-dentistry", number: "07", title: "Pediatric dentistry", eyebrow: "Child-first care", summary: "Gentle care designed to help young patients feel at ease.", overview: "Akshar Dental Clinic offers pediatric dental care with a gentle, child-first approach. Early visits can help children become familiar with dental care while supporting healthier oral routines as they grow.", considerations: ["A calm introduction to the dental visit", "Age-appropriate oral-hygiene support", "Space for parents to ask questions"] },
  { slug: "dental-implants", number: "08", title: "Dental implants", eyebrow: "Replacing missing teeth", summary: "Options for replacing missing teeth and restoring everyday function.", overview: "Dental implants are one option to discuss when replacing missing teeth. A consultation helps the clinic understand your oral health, explain the process, and guide you through the considerations involved.", considerations: ["Review your individual oral-health needs", "Understand the stages involved", "Discuss the questions that matter to you"] },
  { slug: "root-canal-treatment", number: "09", title: "Root canal treatment", eyebrow: "Protecting natural teeth", summary: "Care intended to protect natural teeth and address infection.", overview: "Root canal treatment may be recommended when the inner part of a tooth needs care. The clinic can explain what is being seen, why treatment may be useful, and how the next step is planned.", considerations: ["Understand the reason for the recommendation", "Ask about the treatment process", "Discuss aftercare and follow-up"] },
  { slug: "braces-orthodontics", number: "10", title: "Braces & orthodontics", eyebrow: "Straightening care", summary: "Metal braces or aligner options for a straighter, functional smile.", overview: "Akshar Dental Clinic lists both metal braces and invisible aligner options. Orthodontic planning considers the alignment of your teeth, day-to-day life, and the aesthetic and functional goals you want to discuss.", considerations: ["Explore braces or aligner options", "Talk about function and appearance", "Understand the care plan and timing"] },
  { slug: "full-mouth-rehabilitation", number: "11", title: "Full-mouth rehabilitation", eyebrow: "Coordinated restoration", summary: "Restorative and cosmetic treatment coordinated as one plan.", overview: "Full-mouth rehabilitation brings restorative and cosmetic treatment considerations into a coordinated plan. It is a detailed conversation, built around your oral health, priorities, and the sequence of care that is appropriate for you.", considerations: ["Take a whole-mouth view of your needs", "Understand how treatments can work together", "Discuss priorities and treatment sequencing"] },
];

export const getAksharService = (slug: string | undefined) => aksharServices.find((service) => service.slug === slug);
